name: dkb_retail
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  db_uicomponents:
    path: ../ret_components

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  device_info_plus: 11.2.0
  flutter_riverpod: ^2.5.1
  auto_route: ^10.1.2
  freezed_annotation: ^2.4.4
  #  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.3.5
  gap: ^3.0.1
  fpdart: ^1.1.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  dio: ^5.6.0
  riverpod: ^2.5.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  dart_jsonwebtoken: ^3.2.0
  easy_date_timeline: ^2.0.9
  flutter_email_sender: ^6.0.2

  path_provider: ^2.1.4
  dotted_line: ^3.2.3
  local_session_timeout: ^3.2.0
  local_auth: ^2.3.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.1.7
  plugin_platform_interface: ^2.1.8
  permission_handler: ^11.1.0
  google_maps_flutter: ^2.13.0
  location: ^8.0.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.0.5
  logger: ^2.4.0
  flutter_spinkit: ^5.2.1
  flutter_inappwebview: ^6.1.5
  network_info_plus: ^6.0.1
  fluttertoast: ^8.2.5
  motion_toast: ^2.10.0
  card_swiper: ^3.0.1
  shimmer: ^3.0.0
  pinput: ^5.0.1
  lottie: ^3.1.2
  uuid: ^4.5.1
  jailbreak_root_detection: ^1.1.5
  table_calendar: ^3.0.9
  calendar_date_picker2: ^1.0.2
  syncfusion_flutter_charts:
  image_picker: ^1.2.0
  webview_flutter: ^4.13.0
  crypto: ^3.0.6
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4

  camera: ^0.11.2 # For camera integration
  # google_ml_kit:
  #  google_mlkit_text_recognition: ^0.14.0
  shared_preferences: ^2.3.5
  country_list: ^0.0.5
  scroll_to_index: ^3.0.1

  country_state_city: ^0.1.6
  file_picker: ^8.1.7
  path: ^1.9.0
  smooth_page_indicator: ^1.2.0+3

  gradient_borders: ^1.0.2
  alphabet_list_view: ^1.1.6
  video_player: ^2.10.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  auto_route_generator: ^10.1.2
  json_serializable: ^6.9.0
  flutter_lints: ^6.0.0
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.2
  flutter_localization: ^0.3.3
  db_codegen:
    path: C:\Users\BOSS\Downloads\Dukhan DevOps Docs\jenkins\dkb_retail\ret_components\packages\db_codegen

dependency_overrides:
  intl: ">=0.17.0 <0.21.0"
  calendar_timeline:
    git:
      url: https://github.com/muhammadtalhasultan/calendar_timeline
  android_intent_plus: ^3.1.9

# analyzer: ^7.6.0
# analyzer_plugin: ^0.11.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AppIcon.png"
  # image_path_ios: "assets/images/AppIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/security/
    - assets/video/
    - assets/json/
    - assets/images/
    - assets/icons/login/
    - assets/images/locate_image/
    - assets/images/flags/
    - assets/images/product/
    - assets/lottie/
    - assets/svg/
    - assets/svg/login/
    - assets/images/flags/
    - assets/icons/
    - assets/icons/login/
    - assets/icons/transfer/
    - assets/icons/salary_approval/
    - assets/i18n/
    - assets/json/authentication_code_sent.json
    - assets/json/theme.json
    - assets/evergreen-1.png
    - assets/images.png
    - assets/Screenshot-1.png
    - assets/image.png
    - assets/card.jpeg
    - assets/images/profile.png
    - assets/icons/retail/
    - assets/images/retail/
    - assets/gif/
    - assets/gif/dashboard/
    - assets/json/
    - assets/images/successIcon.jpeg
    - assets/app_theme_regular.json
    - assets/app_theme_private.json

  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/SFPro-Regular.ttf
        - asset: assets/fonts/SFPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFPro-Bold.ttf
          weight: 700
    - family: rubikDiodrumArabic-
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500

    - family: DiodrumArabic
      fonts:
        - asset: assets/fonts/DiodrumArabic-Light.otf
          weight: 300
        - asset: assets/fonts/DiodrumArabic-Regular.otf
          weight: 400
        - asset: assets/fonts/DiodrumArabic-Medium.otf
          weight: 500
        - asset: assets/fonts/DiodrumArabic-SemiBold.otf
          weight: 600
        - asset: assets/fonts/DiodrumArabic-Bold.otf
          weight: 700
