name: Flutter Build - dkb_retail

on:
  push:
    branches: [main]        # trigger on push to main
  pull_request:
    branches: [main]        # trigger on PR to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'   # replace with your Flutter version if needed

      - name: Get dependencies
        run: |
          cd code-folder
          flutter pub get

      - name: Build APK
        run: |
          cd code-folder
          flutter build apk --debug
